skills = [{'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 11584,
  'name': u'Anchoring'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 3363,
  'name': u'Corporation Management'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 3368,
  'name': u'Diplomatic Relations'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 3732,
  'name': u'Empire Control'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 3731,
  'name': u'Megacorp Management'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 12241,
  'name': u'Sovereignty'},
 {'group_id': 266,
  'group_name': u'Corporation Management',
  'id': 3373,
  'name': u'Starbase Defense Management'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 24613,
  'name': u'Advanced Drone Interfacing'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 12484,
  'name': u'Amarr Drone Specialization'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 12487,
  'name': u'Caldari Drone Specialization'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 24241,
  'name': u'Combat Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 23618,
  'name': u'Drone Durability'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3442,
  'name': u'Drone Interfacing'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 12305,
  'name': u'Drone Navigation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 23606,
  'name': u'Drone Sharpshooting'},
 {'group_id': 273, 'group_name': u'Drones', 'id': 3436, 'name': u'Drones'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 23566,
  'name': u'Electronic Warfare Drone Interfacing'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 32339,
  'name': u'Fighter Bombers'},
 {'group_id': 273, 'group_name': u'Drones', 'id': 23069, 'name': u'Fighters'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 12486,
  'name': u'Gallente Drone Specialization'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3441,
  'name': u'Heavy Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3438,
  'name': u'Mining Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 12485,
  'name': u'Minmatar Drone Specialization'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3439,
  'name': u'Repair Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3440,
  'name': u'Salvage Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 3437,
  'name': u'Scout Drone Operation'},
 {'group_id': 273,
  'group_name': u'Drones',
  'id': 23594,
  'name': u'Sentry Drone Interfacing'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 11579,
  'name': u'Cloaking'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 21603,
  'name': u'Cynosural Field Theory'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3427,
  'name': u'Electronic Warfare'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3426,
  'name': u'Electronics'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3432,
  'name': u'Electronics Upgrades'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19760,
  'name': u'Frequency Modulation'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 33000,
  'name': u'Gravimetric Sensor Compensation'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 33001,
  'name': u'Ladar Sensor Compensation'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19759,
  'name': u'Long Distance Jamming'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3428,
  'name': u'Long Range Targeting'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 32999,
  'name': u'Magnetometric Sensor Compensation'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3430,
  'name': u'Multitasking'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 27911,
  'name': u'Projected Electronic Counter Measures'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3435,
  'name': u'Propulsion Jamming'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 33002,
  'name': u'Radar Sensor Compensation'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3433,
  'name': u'Sensor Linking'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19761,
  'name': u'Signal Dispersion'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19766,
  'name': u'Signal Suppression'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3431,
  'name': u'Signature Analysis'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19922,
  'name': u'Signature Focusing'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3551,
  'name': u'Survey'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 4411,
  'name': u'Target Breaker Amplification'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19921,
  'name': u'Target Painting'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3429,
  'name': u'Targeting'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 19767,
  'name': u'Turret Destabilization'},
 {'group_id': 272,
  'group_name': u'Electronics',
  'id': 3434,
  'name': u'Weapon Disruption'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 24572,
  'name': u'Capital Energy Emission Systems'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 24571,
  'name': u'Capital Shield Emission Systems'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 21802,
  'name': u'Capital Shield Operation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 12365,
  'name': u'EM Shield Compensation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3423,
  'name': u'Energy Emission Systems'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3424,
  'name': u'Energy Grid Upgrades'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3418,
  'name': u'Energy Management'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3421,
  'name': u'Energy Pulse Weapons'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3417,
  'name': u'Energy Systems Operation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3413,
  'name': u'Engineering'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 12367,
  'name': u'Explosive Shield Compensation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 12366,
  'name': u'Kinetic Shield Compensation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 21059,
  'name': u'Shield Compensation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3422,
  'name': u'Shield Emission Systems'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3419,
  'name': u'Shield Management'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3416,
  'name': u'Shield Operation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3425,
  'name': u'Shield Upgrades'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 3420,
  'name': u'Tactical Shield Manipulation'},
 {'group_id': 271,
  'group_name': u'Engineering',
  'id': 11566,
  'name': u'Thermic Shield Compensation'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 11207,
  'name': u'Advanced Weapon Upgrades'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 20327,
  'name': u'Capital Energy Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 21666,
  'name': u'Capital Hybrid Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 21667,
  'name': u'Capital Projectile Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3316,
  'name': u'Controlled Bursts'},
 {'group_id': 255, 'group_name': u'Gunnery', 'id': 3300, 'name': u'Gunnery'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12203,
  'name': u'Large Artillery Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12209,
  'name': u'Large Autocannon Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12205,
  'name': u'Large Beam Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12212,
  'name': u'Large Blaster Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3309,
  'name': u'Large Energy Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3307,
  'name': u'Large Hybrid Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3308,
  'name': u'Large Projectile Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12215,
  'name': u'Large Pulse Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12207,
  'name': u'Large Railgun Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12202,
  'name': u'Medium Artillery Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12208,
  'name': u'Medium Autocannon Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12204,
  'name': u'Medium Beam Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12211,
  'name': u'Medium Blaster Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3306,
  'name': u'Medium Energy Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3304,
  'name': u'Medium Hybrid Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3305,
  'name': u'Medium Projectile Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12214,
  'name': u'Medium Pulse Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12206,
  'name': u'Medium Railgun Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3312,
  'name': u'Motion Prediction'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3310,
  'name': u'Rapid Firing'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3311,
  'name': u'Sharpshooter'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12201,
  'name': u'Small Artillery Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 11084,
  'name': u'Small Autocannon Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 11083,
  'name': u'Small Beam Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12210,
  'name': u'Small Blaster Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3303,
  'name': u'Small Energy Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3301,
  'name': u'Small Hybrid Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3302,
  'name': u'Small Projectile Turret'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 12213,
  'name': u'Small Pulse Laser Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 11082,
  'name': u'Small Railgun Specialization'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3315,
  'name': u'Surgical Strike'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 22043,
  'name': u'Tactical Weapon Reconfiguration'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3317,
  'name': u'Trajectory Analysis'},
 {'group_id': 255,
  'group_name': u'Gunnery',
  'id': 3318,
  'name': u'Weapon Upgrades'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 24625,
  'name': u'Advanced Mass Production'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12180,
  'name': u'Arkonor Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12181,
  'name': u'Bistot Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12182,
  'name': u'Crokite Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12183,
  'name': u'Dark Ochre Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 11395,
  'name': u'Deep Core Mining'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 26224,
  'name': u'Drug Manufacturing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 25544,
  'name': u'Gas Cloud Harvesting'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12184,
  'name': u'Gneiss Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12185,
  'name': u'Hedbergite Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12186,
  'name': u'Hemorphite Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 16281,
  'name': u'Ice Harvesting'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 18025,
  'name': u'Ice Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 28585,
  'name': u'Industrial Reconfiguration'},
 {'group_id': 268, 'group_name': u'Industry', 'id': 3380, 'name': u'Industry'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12187,
  'name': u'Jaspet Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12188,
  'name': u'Kernite Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 3387,
  'name': u'Mass Production'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12189,
  'name': u'Mercoxit Processing'},
 {'group_id': 268, 'group_name': u'Industry', 'id': 3386, 'name': u'Mining'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 22578,
  'name': u'Mining Upgrades'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12190,
  'name': u'Omber Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12191,
  'name': u'Plagioclase Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 3388,
  'name': u'Production Efficiency'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12192,
  'name': u'Pyroxeres Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 3389,
  'name': u'Refinery Efficiency'},
 {'group_id': 268, 'group_name': u'Industry', 'id': 3385, 'name': u'Refining'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12193,
  'name': u'Scordite Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12196,
  'name': u'Scrapmetal Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12194,
  'name': u'Spodumain Processing'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 24268,
  'name': u'Supply Chain Management'},
 {'group_id': 268,
  'group_name': u'Industry',
  'id': 12195,
  'name': u'Veldspar Processing'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 20494,
  'name': u'Armored Warfare'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 11569,
  'name': u'Armored Warfare Specialist'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 24764,
  'name': u'Fleet Command'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 20495,
  'name': u'Information Warfare'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3352,
  'name': u'Information Warfare Specialist'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3348,
  'name': u'Leadership'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 22552,
  'name': u'Mining Director'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 22536,
  'name': u'Mining Foreman'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3350,
  'name': u'Siege Warfare'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3351,
  'name': u'Siege Warfare Specialist'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3349,
  'name': u'Skirmish Warfare'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 11572,
  'name': u'Skirmish Warfare Specialist'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 3354,
  'name': u'Warfare Link Specialist'},
 {'group_id': 258,
  'group_name': u'Leadership',
  'id': 11574,
  'name': u'Wing Command'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 32797,
  'name': u'Armor Resistance Phasing'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26253,
  'name': u'Armor Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26254,
  'name': u'Astronautics Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3398,
  'name': u'Battleship Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 24568,
  'name': u'Capital Remote Armor Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 27936,
  'name': u'Capital Remote Hull Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 21803,
  'name': u'Capital Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 22242,
  'name': u'Capital Ship Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3397,
  'name': u'Cruiser Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26255,
  'name': u'Drones Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26256,
  'name': u'Electronic Superiority Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 22806,
  'name': u'EM Armor Compensation'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26258,
  'name': u'Energy Weapon Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 22807,
  'name': u'Explosive Armor Compensation'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3395,
  'name': u'Frigate Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3394,
  'name': u'Hull Upgrades'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26259,
  'name': u'Hybrid Weapon Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3396,
  'name': u'Industrial Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26252,
  'name': u'Jury Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 22808,
  'name': u'Kinetic Armor Compensation'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26260,
  'name': u'Launcher Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3392,
  'name': u'Mechanics'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 28880,
  'name': u'Nanite Interfacing'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 28879,
  'name': u'Nanite Operation'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3400,
  'name': u'Outpost Construction'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26257,
  'name': u'Projectile Weapon Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 16069,
  'name': u'Remote Armor Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 27902,
  'name': u'Remote Hull Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 3393,
  'name': u'Repair Systems'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 25863,
  'name': u'Salvaging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 26261,
  'name': u'Shield Rigging'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 27906,
  'name': u'Tactical Logistics Reconfiguration'},
 {'group_id': 269,
  'group_name': u'Mechanics',
  'id': 22809,
  'name': u'Thermic Armor Compensation'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3322,
  'name': u'Auto-Targeting Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 28073,
  'name': u'Bomb Deployment'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 32435,
  'name': u'Citadel Cruise Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 21668,
  'name': u'Citadel Torpedoes'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20212,
  'name': u'Cruise Missile Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3326,
  'name': u'Cruise Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3323,
  'name': u'Defender Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20312,
  'name': u'Guided Missile Precision'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 25718,
  'name': u'Heavy Assault Missile Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 25719,
  'name': u'Heavy Assault Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20211,
  'name': u'Heavy Missile Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3324,
  'name': u'Heavy Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20210,
  'name': u'Light Missile Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3321,
  'name': u'Light Missiles'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 12441,
  'name': u'Missile Bombardment'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3319,
  'name': u'Missile Launcher Operation'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 12442,
  'name': u'Missile Projection'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 21071,
  'name': u'Rapid Launch'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20209,
  'name': u'Rocket Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3320,
  'name': u'Rockets'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20314,
  'name': u'Target Navigation Prediction'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20213,
  'name': u'Torpedo Specialization'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 3325,
  'name': u'Torpedoes'},
 {'group_id': 256,
  'group_name': u'Missile Launcher Operation',
  'id': 20315,
  'name': u'Warhead Upgrades'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3452,
  'name': u'Acceleration Control'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3450,
  'name': u'Afterburner'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3453,
  'name': u'Evasive Maneuvering'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3451,
  'name': u'Fuel Conservation'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3454,
  'name': u'High Speed Maneuvering'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 21611,
  'name': u'Jump Drive Calibration'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3456,
  'name': u'Jump Drive Operation'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 21610,
  'name': u'Jump Fuel Conservation'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 4385,
  'name': u'Micro Jump Drive Operation'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3449,
  'name': u'Navigation'},
 {'group_id': 275,
  'group_name': u'Navigation',
  'id': 3455,
  'name': u'Warp Drive Operation'},
 {'group_id': 1044,
  'group_name': u'Planet Management',
  'id': 2403,
  'name': u'Advanced Planetology'},
 {'group_id': 1044,
  'group_name': u'Planet Management',
  'id': 2505,
  'name': u'Command Center Upgrades'},
 {'group_id': 1044,
  'group_name': u'Planet Management',
  'id': 2495,
  'name': u'Interplanetary Consolidation'},
 {'group_id': 1044,
  'group_name': u'Planet Management',
  'id': 2406,
  'name': u'Planetology'},
 {'group_id': 1044,
  'group_name': u'Planet Management',
  'id': 13279,
  'name': u'Remote Sensing'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24624,
  'name': u'Advanced Laboratory Operation'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 23087,
  'name': u'Amarr Encryption Methods'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11444,
  'name': u'Amarrian Starship Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 13278,
  'name': u'Archaeology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3410,
  'name': u'Astrogeology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 25811,
  'name': u'Astrometric Acquisition'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 25810,
  'name': u'Astrometric Pinpointing'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 25739,
  'name': u'Astrometric Rangefinding'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3412,
  'name': u'Astrometrics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11487,
  'name': u'Astronautic Engineering'},
 {'group_id': 270, 'group_name': u'Science', 'id': 3405, 'name': u'Biology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 21790,
  'name': u'Caldari Encryption Methods'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11454,
  'name': u'Caldari Starship Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24606,
  'name': u'Cloning Facility Operation'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3411,
  'name': u'Cybernetics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 30324,
  'name': u'Defensive Subsystem Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24563,
  'name': u'Doomsday Operation'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11448,
  'name': u'Electromagnetic Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11453,
  'name': u'Electronic Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 30326,
  'name': u'Electronic Subsystem Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 30325,
  'name': u'Engineering Subsystem Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 23121,
  'name': u'Gallente Encryption Methods'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11450,
  'name': u'Gallentean Starship Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11446,
  'name': u'Graviton Physics'},
 {'group_id': 270, 'group_name': u'Science', 'id': 21718, 'name': u'Hacking'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11433,
  'name': u'High Energy Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11443,
  'name': u'Hydromagnetic Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24242,
  'name': u'Infomorph Psychology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24562,
  'name': u'Jump Portal Generation'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3406,
  'name': u'Laboratory Operation'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11447,
  'name': u'Laser Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11452,
  'name': u'Mechanical Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3409,
  'name': u'Metallurgy'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 21791,
  'name': u'Minmatar Encryption Methods'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11445,
  'name': u'Minmatar Starship Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11529,
  'name': u'Molecular Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 25538,
  'name': u'Nanite Control'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11442,
  'name': u'Nanite Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 25530,
  'name': u'Neurotoxin Recovery'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11451,
  'name': u'Nuclear Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 30327,
  'name': u'Offensive Subsystem Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11441,
  'name': u'Plasma Physics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 30788,
  'name': u'Propulsion Subsystem Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11455,
  'name': u'Quantum Physics'},
 {'group_id': 270, 'group_name': u'Science', 'id': 3403, 'name': u'Research'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 12179,
  'name': u'Research Project Management'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 3408,
  'name': u'Reverse Engineering'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 11449,
  'name': u'Rocket Science'},
 {'group_id': 270, 'group_name': u'Science', 'id': 3402, 'name': u'Science'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 24270,
  'name': u'Scientific Networking'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 21789,
  'name': u'Sleeper Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 23123,
  'name': u'Takmahl Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 20433,
  'name': u'Talocan Technology'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 28164,
  'name': u'Thermodynamics'},
 {'group_id': 270,
  'group_name': u'Science',
  'id': 23124,
  'name': u'Yan Jung Technology'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3359,
  'name': u'Connections'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3361,
  'name': u'Criminal Connections'},
 {'group_id': 278, 'group_name': u'Social', 'id': 3357, 'name': u'Diplomacy'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3894,
  'name': u'Distribution Connections'},
 {'group_id': 278, 'group_name': u'Social', 'id': 3358, 'name': u'Fast Talk'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3893,
  'name': u'Mining Connections'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3356,
  'name': u'Negotiation'},
 {'group_id': 278,
  'group_name': u'Social',
  'id': 3895,
  'name': u'Security Connections'},
 {'group_id': 278, 'group_name': u'Social', 'id': 3355, 'name': u'Social'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20342,
  'name': u'Advanced Spaceship Command'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3339,
  'name': u'Amarr Battleship'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 24311,
  'name': u'Amarr Carrier'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3335,
  'name': u'Amarr Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20525,
  'name': u'Amarr Dreadnought'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20524,
  'name': u'Amarr Freighter'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3331,
  'name': u'Amarr Frigate'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3343,
  'name': u'Amarr Industrial'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 30650,
  'name': u'Amarr Strategic Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3347,
  'name': u'Amarr Titan'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12095,
  'name': u'Assault Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12099,
  'name': u'Battlecruisers'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 28656,
  'name': u'Black Ops'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3338,
  'name': u'Caldari Battleship'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 24312,
  'name': u'Caldari Carrier'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3334,
  'name': u'Caldari Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20530,
  'name': u'Caldari Dreadnought'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20526,
  'name': u'Caldari Freighter'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3330,
  'name': u'Caldari Frigate'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3342,
  'name': u'Caldari Industrial'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 30651,
  'name': u'Caldari Strategic Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3346,
  'name': u'Caldari Titan'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 28374,
  'name': u'Capital Industrial Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20533,
  'name': u'Capital Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 23950,
  'name': u'Command Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12093,
  'name': u'Covert Ops'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12097,
  'name': u'Destroyers'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 28615,
  'name': u'Electronic Attack Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 22551,
  'name': u'Exhumers'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3336,
  'name': u'Gallente Battleship'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 24313,
  'name': u'Gallente Carrier'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3332,
  'name': u'Gallente Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20531,
  'name': u'Gallente Dreadnought'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20527,
  'name': u'Gallente Freighter'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3328,
  'name': u'Gallente Frigate'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3340,
  'name': u'Gallente Industrial'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 30652,
  'name': u'Gallente Strategic Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3344,
  'name': u'Gallente Titan'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 16591,
  'name': u'Heavy Assault Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 28609,
  'name': u'Heavy Interdictors'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 29637,
  'name': u'Industrial Command Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12092,
  'name': u'Interceptors'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12098,
  'name': u'Interdictors'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 29029,
  'name': u'Jump Freighters'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 12096,
  'name': u'Logistics'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 28667,
  'name': u'Marauders'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 17940,
  'name': u'Mining Barge'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 32918,
  'name': u'Mining Frigate'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3337,
  'name': u'Minmatar Battleship'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 24314,
  'name': u'Minmatar Carrier'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3333,
  'name': u'Minmatar Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20532,
  'name': u'Minmatar Dreadnought'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 20528,
  'name': u'Minmatar Freighter'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3329,
  'name': u'Minmatar Frigate'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3341,
  'name': u'Minmatar Industrial'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 30653,
  'name': u'Minmatar Strategic Cruiser'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3345,
  'name': u'Minmatar Titan'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3184,
  'name': u'ORE Industrial'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 22761,
  'name': u'Recon Ships'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 3327,
  'name': u'Spaceship Command'},
 {'group_id': 257,
  'group_name': u'Spaceship Command',
  'id': 19719,
  'name': u'Transport Ships'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30532,
  'name': u'Amarr Defensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30536,
  'name': u'Amarr Electronic Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30539,
  'name': u'Amarr Engineering Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30537,
  'name': u'Amarr Offensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30538,
  'name': u'Amarr Propulsion Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30544,
  'name': u'Caldari Defensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30542,
  'name': u'Caldari Electronic Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30548,
  'name': u'Caldari Engineering Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30549,
  'name': u'Caldari Offensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30552,
  'name': u'Caldari Propulsion Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30540,
  'name': u'Gallente Defensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30541,
  'name': u'Gallente Electronic Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30546,
  'name': u'Gallente Engineering Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30550,
  'name': u'Gallente Offensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30553,
  'name': u'Gallente Propulsion Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30545,
  'name': u'Minmatar Defensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30543,
  'name': u'Minmatar Electronic Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30547,
  'name': u'Minmatar Engineering Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30551,
  'name': u'Minmatar Offensive Systems'},
 {'group_id': 989,
  'group_name': u'Subsystems',
  'id': 30554,
  'name': u'Minmatar Propulsion Systems'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 16622, 'name': u'Accounting'},
 {'group_id': 274,
  'group_name': u'Trade',
  'id': 3446,
  'name': u'Broker Relations'},
 {'group_id': 274,
  'group_name': u'Trade',
  'id': 25235,
  'name': u'Contracting'},
 {'group_id': 274,
  'group_name': u'Trade',
  'id': 25233,
  'name': u'Corporation Contracting'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 16595, 'name': u'Daytrading'},
 {'group_id': 274,
  'group_name': u'Trade',
  'id': 16597,
  'name': u'Margin Trading'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 16598, 'name': u'Marketing'},
 {'group_id': 274,
  'group_name': u'Trade',
  'id': 16594,
  'name': u'Procurement'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 3444, 'name': u'Retail'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 3443, 'name': u'Trade'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 18580, 'name': u'Tycoon'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 3447, 'name': u'Visibility'},
 {'group_id': 274, 'group_name': u'Trade', 'id': 16596, 'name': u'Wholesale'}]